Repository Leets-Official/GachTaxi-FE, pull requests merged in 2025-01, with the labels that each got.

#9 Style: 테일윈드 확장 변수 설정
  tailwind.config.js
Labels: design

#11 Refactor: 회원가입 UI 구현 및 로직 재작성
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icon/backIcon.svg
  src/assets/icon/basicProfileIcon.svg
  src/assets/icon/cameraIcon.svg
  src/components/commons/Button.tsx
  src/components/commons/Input.tsx
  src/components/sign/AuthCodeVerification.tsx
  src/components/sign/EmailVerification.tsx
  src/components/sign/SignInForm.tsx
  src/components/sign/SignUpForm.tsx
  src/components/sign/userInfoVerification/GenderSelect.tsx
  src/components/sign/userInfoVerification/ProfileImageUpload.tsx
  src/components/sign/userInfoVerification/index.tsx
  src/hooks/index.tsx
  src/hooks/useVerificationTimer.ts
  src/index.css
  src/libs/schemas/auth.ts
  src/pages/Layout.tsx
  src/pages/NotFound.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up/UserInfoPage.tsx
  src/pages/sign-up/VerificationPage.tsx
  src/pages/sign-up/index.tsx
  src/types/auth.d.ts
  src/utils/index.tsx
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.node.json
  vercel.json
  vite.config.ts
Labels: enhancement

#15 Feat: 구글 로그인 로직 구현
  package.json
  pnpm-lock.yaml
  src/components/landing/GoogleLoginButton.tsx
  src/components/landing/KakaoLoginButton.tsx
  src/components/sign/AuthCodeVerification.tsx
  src/components/sign/userInfoVerification/ProfileImageUpload.tsx
  src/pages/landing/FirstLanding.tsx
  src/pages/landing/index.tsx
Labels: feat

#17 Feat: 공통 모달 컴포넌트 구현 및 약관 동의 UI 구현
  index.html
  src/App.tsx
  src/assets/icon/agreeLinkIcon.svg
  src/components/commons/Button.tsx
  src/components/commons/Checkbox.tsx
  src/components/commons/Input.tsx
  src/components/modal/AgreementModal.tsx
  src/components/modal/index.tsx
  src/components/sign/AuthCodeVerification.tsx
  src/components/sign/EmailVerification.tsx
  src/components/sign/userInfoVerification/GenderSelect.tsx
  src/components/sign/userInfoVerification/index.tsx
  src/constants/index.tsx
  src/contexts/ModalContext.tsx
  src/hooks/useVerificationTimer.ts
  src/libs/schemas/auth.ts
  src/pages/sign-up/UserInfoPage.tsx
  src/pages/sign-up/VerificationPage.tsx
  src/pages/sign-up/index.tsx
  src/types/auth.d.ts
  tailwind.config.js
  vercel.json
Labels: feat

#20 Feat: 홈 화면 네비바 구현
  src/App.tsx
  src/assets/icon/friendsIcon.svg
  src/assets/icon/homeIcon.svg
  src/assets/icon/matchIcon.svg
  src/components/home/Navbar.tsx
  src/components/modal/index.tsx
  src/pages/Layout.tsx
  src/pages/home/index.tsx
  src/pages/landing/index.tsx
  src/pages/sign-up/UserInfoPage.tsx
  src/pages/sign-up/index.tsx
Labels: feat

#23 Feat: 카카오 로그인 로직 구현
  .gitignore
  src/App.tsx
  src/components/landing/KakaoLoginButton.tsx
  src/components/landing/KakaoLoginLoading.tsx
  src/components/landing/LandingHeader.tsx
  vite.config.ts
Labels: feat

#26 Feat: 마이 페이지 UI 구현
  src/App.tsx
  src/assets/icon/myPageModifyButton.svg
  src/assets/icon/myPageProfile.svg
  src/components/landing/KakaoLoginLoading.tsx
  src/components/my-page/MyPageButton.tsx
  src/components/my-page/MyProfileHeader.tsx
  src/constants/index.tsx
  src/index.css
  src/pages/my-page/Inquiry.tsx
  src/pages/my-page/Notice.tsx
  src/pages/my-page/Notification.tsx
  src/pages/my-page/PhoneVerification.tsx
  src/pages/my-page/Usage.tsx
  src/pages/my-page/index.tsx
  tailwind.config.js
Labels: feat, design

#28 Feat: 카카오맵 api 사용한 홈 지도 연결
  index.html
  src/components/home/KakaoMap.tsx
  src/components/home/MatchingSheet.tsx
  src/components/home/Navbar.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/constants/index.tsx
  src/index.css
  src/libs/apis/kakaoMobility.api.ts
  src/pages/home/index.tsx
Labels: feat

#34 Feat: 수동 매칭 등록 페이지 UI 구현
  src/App.tsx
  src/components/commons/BackButton.tsx
  src/components/home/KakaoMap.tsx
  src/components/home/MatchingSheet.tsx
  src/components/home/autoMatching/InviteMembers.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/autoMatching/SelectTags.tsx
  src/components/home/autoMatching/index.tsx
  src/components/home/autoMatching/inviteMembers/MemberItem.tsx
  src/components/home/autoMatching/inviteMembers/index.tsx
  src/components/home/autoMatching/selectTags/TagItem.tsx
  src/components/home/autoMatching/selectTags/index.tsx
  src/components/home/manualMatching/HistoryPage.tsx
  src/components/home/manualMatching/MatchingInfoItem.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/MyMatchingPage.tsx
  src/components/home/manualMatching/index.tsx
  src/components/manual-register/AddContent.tsx
  src/components/manual-register/timeSelect/HourSelect.tsx
  src/components/manual-register/timeSelect/MinuteSelect.tsx
  src/components/manual-register/timeSelect/PeriodSelect.tsx
  src/components/manual-register/timeSelect/index.tsx
  src/components/sign/EmailVerification.tsx
  src/constants/agreeValues.constant.ts
  src/constants/buttonData.constant.ts
  src/constants/index.ts
  src/constants/index.tsx
  src/constants/routes.constant.ts
  src/constants/styles.constant.ts
  src/constants/thresholds.constant.ts
  src/constants/timeOptions.constant.ts
  src/libs/schemas/match.ts
  src/pages/manual-register/index.tsx
  src/pages/sign-up/index.tsx
  src/types/match.d.ts
  src/utils/formatTimeLikeTimer.ts
  src/utils/formatTimeToSelect.ts
  src/utils/handleDragEnd.ts
  src/utils/index.ts
Labels: feat

#35 feat: api 로직에 사용할 공통 인스턴스 작성
  src/libs/apis/clients.ts
Labels: feat

#40 fix : 소셜 로그인 api 분리
  src/components/landing/KakaoLoginLoading.tsx
  src/libs/apis/kakaoLogin.api.ts
Labels: fix

#38 Feat: 수동 매칭 상세 페이지 UI 구현
  src/App.tsx
  src/assets/icon/locationTaxiIcon.svg
  src/components/commons/Button.tsx
  src/components/sign/userInfoVerification/index.tsx
  src/pages/manual-matching-detail/index.tsx
  src/pages/sign-up/index.tsx
Labels: feat

#42 Fix: axiso client 로직 수정
  src/components/landing/KakaoLoginLoading.tsx
  src/libs/apis/clients.ts
  src/libs/apis/kakaoLogin.api.ts
Labels: fix

#44 Refactor: 바로/수동 매칭 로직 최신화
  index.html
  src/components/commons/BackButton.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/autoMatching/index.tsx
  src/components/home/autoMatching/inviteMembers/index.tsx
  src/components/home/autoMatching/selectTags/index.tsx
  src/hooks/useGeoLocation.ts
  src/libs/apis/getCoordinateByAddress.ts
  src/libs/schemas/match.ts
  src/pages/manual-register/index.tsx
  src/pages/sign-up/index.tsx
  src/types/match.d.ts
Labels: refactor

#46 Feat: 토스트 로직 구현
  index.html
  src/App.tsx
  src/components/index.tsx
  src/components/modal/index.tsx
  src/components/toast/index.tsx
  src/contexts/ModalContext.tsx
  src/contexts/ToastContext.tsx
Labels: feat

#48 Feat: 전화번호 인증 페이지 UI 및 로직 구현
  src/components/home/manualMatching/MatchingInfoItem.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/phoneVerification/AuthCodeVerificationForPhone.tsx
  src/components/phoneVerification/PhoneVerification.tsx
  src/constants/buttonData.constant.ts
  src/constants/index.ts
  src/hooks/useChangeButtonData.tsx
  src/index.css
  src/libs/schemas/auth.ts
  src/pages/my-page/PhoneVerification.tsx
  src/pages/my-page/PhoneVerificationPage.tsx
  src/pages/my-page/index.tsx
  src/pages/phoneVerification/index.tsx
  src/pages/sign-up/index.tsx
  src/types/auth.d.ts
Labels: feat

#45 feat: 매칭 채팅 UI 구현
  src/App.tsx
  src/assets/icon/callTaxi.svg
  src/assets/icon/cancelMatching.svg
  src/assets/icon/chatPlus.svg
  src/assets/icon/chatSend.svg
  src/assets/icon/chatX.svg
  src/assets/icon/closeMatching.svg
  src/assets/icon/sendAccount.svg
  src/components/chat/InviteMessage.tsx
  src/components/chat/MessageInput.tsx
  src/components/chat/NewMessage.tsx
  src/components/chat/bottomMenu/MenuItem.tsx
  src/components/chat/bottomMenu/index.tsx
  src/components/chat/messageList/index.tsx
  src/components/chat/messageList/renderMyMessage.tsx
  src/components/chat/messageList/renderOtherMessage.tsx
  src/constants/index.ts
  src/constants/menuItems.constant.ts
  src/libs/apis/chat/MessageList.api.ts
  src/pages/chat/index.tsx
Labels: fix, design

#54 Fix: 바로, 수동 매칭 시 내 위치 정보 불러오기 로직 수정
  src/components/home/autoMatching/index.tsx
  src/hooks/useGeoLocation.ts
  src/pages/manual-register/index.tsx
Labels: fix

#59 Refactor: 수동 매칭 리스트의 아이템 디자인 및 로직 변경
  src/App.tsx
  src/components/commons/Button.tsx
  src/components/home/manualMatching/MatchingInfoItem.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/index.tsx
  src/components/home/manualMatching/matchingInfoItem/Tags.tsx
  src/components/home/manualMatching/matchingInfoItem/index.tsx
  src/components/modal/MatchingComplete.tsx
  src/components/modal/index.tsx
  src/components/toast/index.tsx
  src/contexts/ModalContext.tsx
  src/pages/manual-matching-detail/index.tsx
Labels: feat

#62 Feat: 마이 매칭 페이지 UI 작성
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/MyMatchingPage.tsx
  src/components/home/manualMatching/index.tsx
  src/components/home/manualMatching/matchingInfoItem/index.tsx
Labels: feat

#63 Feat: 친구 목록 및 블랙리스트 UI 작성
  src/assets/icon/basicProfileIcon.svg
  src/assets/icon/blackListDeleteIcon.svg
  src/assets/icon/friendSendIcon.svg
  src/assets/icon/friendSettingIcon.svg
  src/components/home/BottomSheet.tsx
  src/components/home/FriendList/BlackInfoItem.tsx
  src/components/home/FriendList/BlackListPage.tsx
  src/components/home/FriendList/FriendInfoItem.tsx
  src/components/home/FriendList/FriendListPage.tsx
  src/components/home/FriendList/index.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/autoMatching/index.tsx
  src/components/modal/FriendDeleteOrBlack.tsx
  src/components/sign/userInfoVerification/ProfileImageUpload.tsx
  src/components/toast/index.tsx
  src/pages/home/index.tsx
Labels: feat

#65 Feat: EventSource를 구현하는 커스텀 EventSource 구현
  src/components/home/autoMatching/index.tsx
  src/utils/EventSourcePolyfill.ts
Labels: feat

#67 Feat: 친구 요청 페이지 UI 및 로직, 빈 페이지 UI 작성
  src/App.tsx
  src/assets/icon/lengthZeroIcon.svg
  src/components/emptyView/index.tsx
  src/components/home/FriendList/BlackInfoItem.tsx
  src/components/home/FriendList/BlackListPage.tsx
  src/components/home/FriendList/FriendListPage.tsx
  src/components/home/FriendList/index.tsx
  src/components/home/autoMatching/index.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/MyMatchingPage.tsx
  src/components/home/manualMatching/index.tsx
  src/components/toast/index.tsx
  src/contexts/ToastContext.tsx
  src/libs/schemas/match.ts
  src/libs/schemas/request.ts
  src/pages/friend-request/index.tsx
  src/pages/manual-register/index.tsx
  src/types/requset.d.ts
Labels: feat

#72 feat: 마이페이지 모달 UI
  src/components/commons/Button.tsx
  src/components/modal/MyPageModal.tsx
  src/components/my-page/LogOutButton.tsx
  src/hooks/index.ts
  src/hooks/useChangeButtonData.tsx
  src/hooks/useLogout.ts
  src/hooks/useWithdraw.ts
  src/libs/apis/withdrawUser.api.ts
Labels: feat, design

#73 Feat: 알림창 UI 구현
  src/App.tsx
  src/components/home/Navbar.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/autoMatching/index.tsx
  src/components/notification/FriendRequestNotification.tsx
  src/components/notification/MatchingNotification.tsx
  src/components/notification/index.tsx
  src/pages/manual-register/index.tsx
  src/pages/notification/index.tsx
Labels: feat

#75 Feat: 프로필 수정 UI 구현
  src/components/my-page/MyProfileHeader.tsx
  src/pages/my-page/EditProfilePage.tsx
  src/pages/my-page/index.tsx
Labels: feat, design

#74 Feat: 택시 호출 모달 UI 구현
  src/components/chat/bottomMenu/index.tsx
  src/components/modal/CallTaxiModal.tsx
Labels: feat, design

#76 Feat: 로딩창 UI 구현
  src/assets/icon/loadingTaxi.svg
  src/components/landing/KakaoLoginLoading.tsx
  src/components/loading/index.tsx
Labels: feat, design

#77 Refactor: Zustand 사용한 로직 개선
  package.json
  pnpm-lock.yaml
  src/components/home/BottomSheet.tsx
  src/components/home/KakaoMap.tsx
  src/components/home/Navbar.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/autoMatching/index.tsx
  src/pages/home/index.tsx
  src/pages/manual-register/index.tsx
  src/store/useLocationStore.ts
  src/store/useSheetStore.ts
  src/utils/getCenterPoint.ts
Labels: feat, refactor

#79 Feat: 회원가입 플로우 API 로직 작성
  src/assets/icon/imageCancelIcon.svg
  src/components/home/KakaoMap.tsx
  src/components/home/autoMatching/index.tsx
  src/components/landing/GoogleLoginButton.tsx
  src/components/modal/AgreementModal.tsx
  src/components/sign/AuthCodeVerification.tsx
  src/components/sign/EmailVerification.tsx
  src/components/sign/userInfoVerification/ProfileImageUpload.tsx
  src/components/sign/userInfoVerification/index.tsx
  src/hooks/useUploadImage.ts
  src/libs/apis/auth/getImageUrl.api.ts
  src/libs/apis/auth/index.ts
  src/libs/apis/auth/requestAgreement.ts
  src/libs/apis/auth/requestEmailVerification.api.ts
  src/libs/apis/auth/requestUserInfo.ts
  src/libs/apis/auth/verifyAuthCode.api.ts
  src/libs/apis/axiosError.api.ts
  src/libs/apis/clients.ts
  src/libs/apis/googleLogin.api.ts
  src/libs/schemas/auth.ts
  src/pages/my-page/EditProfilePage.tsx
  src/types/auth.d.ts
Labels: feat

#81 Feat: 실시간 채팅 기능 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/chat/MessageInput.tsx
  src/components/chat/messageList/index.tsx
  src/components/chat/messageList/renderMyMessage.tsx
  src/components/chat/messageList/renderOtherMessage.tsx
  src/hooks/useWebSocket.ts
  src/libs/apis/chat/MessageList.api.ts
  src/libs/apis/chat/getChatMessages.ts
  src/pages/chat/index.tsx
  src/types/chat.d.ts
  src/types/sockjs-client.d.ts
  vite.config.ts
Labels: feat

#83 Fix: 구글 oauth 로직 수정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/landing/GoogleLoginButton.tsx
  src/components/landing/GoogleLoginLoading.tsx
  src/components/landing/KakaoLoginButton.tsx
  src/libs/apis/clients.ts
  src/libs/apis/googleLogin.api.ts
  src/pages/landing/index.tsx
Labels: fix

#86 Feat: 실시간 채팅 api 연결
  src/assets/icon/firstLandingPage.png
  src/assets/icon/firstLandingPage.svg
  src/assets/icon/lastLandingPage.png
  src/assets/icon/secondLanding.svg
  src/assets/icon/secondLandingPage.png
  src/components/chat/MessageInput.tsx
  src/components/chat/NewMessage.tsx
  src/components/chat/bottomMenu/index.tsx
  src/components/chat/messageList/index.tsx
  src/components/loading/index.tsx
  src/constants/landingText.constant.ts
  src/hooks/useWebSocket.ts
  src/index.css
  src/libs/apis/chat/getChatMessages.ts
  src/libs/apis/getChatMessages.ts
  src/libs/apis/handleExitChatRoom.ts
  src/pages/chat/index.tsx
  src/pages/landing/FirstLanding.tsx
  src/pages/landing/LastLanding.tsx
  src/pages/landing/SecondLanding.tsx
  src/types/chat.d.ts
Labels: feat

#89 Feat: 회원가입 플로우 수정
  src/App.tsx
  src/assets/icon/spinnerIcon.svg
  src/components/commons/Button.tsx
  src/components/home/Navbar.tsx
  src/components/landing/GoogleLoginLoading.tsx
  src/components/landing/KakaoLoginLoading.tsx
  src/components/landing/LandingHeader.tsx
  src/components/modal/AgreementModal.tsx
  src/components/my-page/MyProfileHeader.tsx
  src/components/sign/AuthCodeVerification.tsx
  src/components/sign/EmailVerification.tsx
  src/components/sign/userInfoVerification/ProfileImageUpload.tsx
  src/components/sign/userInfoVerification/index.tsx
  src/hooks/useLogout.ts
  src/hooks/useRequestStatus.ts
  src/hooks/useUploadImage.ts
  src/index.css
  src/libs/apis/auth/getImageUrl.api.ts
  src/libs/apis/auth/getPresignedUrl.ts
  src/pages/ProtectRoute.tsx
  src/pages/my-page/EditProfilePage.tsx
  src/pages/my-page/PhoneVerificationPage.tsx
  src/store/useUserStore.ts
  src/types/auth.d.ts
Labels: refactor

#91 Fix: 채팅방 api 연결
  src/components/chat/ExitMessage.tsx
  src/components/chat/InviteMessage.tsx
  src/components/chat/MessageInput.tsx
  src/components/chat/bottomMenu/index.tsx
  src/components/chat/messageList/index.tsx
  src/components/chat/messageList/renderOtherMessage.tsx
  src/components/chat/modal/ReportModal.tsx
  src/components/modal/CancelTaxiModal.tsx
  src/components/modal/CloseMatching.tsx
  src/hooks/useWebSocket.ts
  src/libs/apis/getChatMessages.ts
  src/libs/apis/handleExitChatRoom.ts
  src/pages/chat/index.tsx
  src/pages/landing/FirstLanding.tsx
  src/pages/landing/LastLanding.tsx
  src/pages/landing/SecondLanding.tsx
  src/types/chat.d.ts
Labels: fix
