Repository Leets-Official/GachTaxi-FE, pull requests merged in 2025-02, with the labels that each got.

#93 Refactor: SSE 이벤트 구독 전역 객체로 리팩토링 및 사용 로직 최적화
  src/App.tsx
  src/assets/icon/largePlusIcon.svg
  src/components/home/autoMatching/index.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/MyMatchingPage.tsx
  src/components/matchingInfo/TImer.tsx
  src/components/sign/EmailVerification.tsx
  src/libs/apis/matching/startAutoMatching.api.ts
  src/pages/manual-register/index.tsx
  src/pages/mathcing/index.tsx
  src/store/useSSEStore.ts
  src/store/useTimerStore.ts
  src/types/match.d.ts
  tailwind.config.js
Labels: feat, refactor

#94 Feat: 알림리스트 API 연동 및 요청 로직 작성
  src/assets/icon/agreeLinkIcon.svg
  src/assets/icon/spinnerIcon.svg
  src/components/emptyView/index.tsx
  src/components/home/Navbar.tsx
  src/components/notification/FriendRequestNotification.tsx
  src/components/notification/MatchingNotification.tsx
  src/components/notification/index.tsx
  src/hooks/mutations/useDeleteNotification.ts
  src/hooks/queries/useInfiniteScroll.ts
  src/hooks/queries/useNotification.ts
  src/libs/apis/notification/deleteNotification.api.ts
  src/libs/apis/notification/getNotifications.api.ts
  src/libs/apis/notification/getUnreadNotification.api.ts
  src/libs/apis/notification/index.ts
  src/pages/notification/index.tsx
  src/store/useIntersectionObserver.ts
  src/types/notification.d.ts
  src/utils/formatToKoreanTIme.ts
Labels: feat

#96 Feat: 채팅방 택시 호출 구현
  src/App.tsx
  src/assets/icon/kakaoT.svg
  src/assets/icon/tadaT.svg
  src/assets/icon/tmoneyGo.svg
  src/assets/icon/uberT.svg
  src/components/chat/bottomMenu/index.tsx
  src/components/modal/CallTaxiModal.tsx
  src/libs/apis/handleExitChatRoom.ts
  src/pages/chat/CallTaxi.tsx
Labels: feat, design

#98 fix: 택시 호출 링크 수정
  src/pages/chat/CallTaxi.tsx
Labels: fix

#104 Feat: 채팅방 방장 여부 체크
  src/components/chat/bottomMenu/index.tsx
  src/hooks/useWebSocket.ts
Labels: feat, design

#106 Feat: 채팅방 친구추가 블랙리스트 api 연결
  src/components/chat/messageList/index.tsx
  src/components/chat/messageList/renderOtherMessage.tsx
  src/components/chat/modal/ReportModal.tsx
  src/hooks/useWebSocket.ts
  src/libs/apis/blacklist/postBlackList.api.ts
  src/libs/apis/friend/postFriends.api.ts
  src/utils/EventSourcePolyfill.ts
Labels: feat

#110 Feat: 수동, 마이 매칭 API 연동
  src/components/home/autoMatching/selectTags/index.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/MyMatchingPage.tsx
  src/components/home/manualMatching/index.tsx
  src/components/home/manualMatching/matchingInfoItem/Tags.tsx
  src/components/home/manualMatching/matchingInfoItem/index.tsx
  src/constants/index.ts
  src/constants/tags.constant.ts
  src/hooks/queries/useManualMatchingList.ts
  src/hooks/queries/useMyMatchingList.ts
  src/libs/apis/manual/createManualMatchingRoom.api.ts
  src/libs/apis/manual/exitManualMatchingRoom.api.ts
  src/libs/apis/manual/getManualMatchingList.api.ts
  src/libs/apis/manual/getMyMatchingList.api.ts
  src/libs/apis/manual/joinManualMatchingRoom.api.ts
  src/libs/schemas/match.ts
  src/pages/manual-register/index.tsx
  src/types/manual.d.ts
  src/types/match.d.ts
Labels: feat

#111 Feat: 마이페이지 수정
  src/components/chat/bottomMenu/index.tsx
  src/components/chat/modal/sendAccountModal.tsx
  src/components/commons/Input.tsx
  src/components/sign/userInfoVerification/ProfileImageUpload.tsx
  src/libs/apis/updateUserProfile.api.ts
  src/libs/schemas/auth.ts
  src/pages/mathcing/index.tsx
  src/pages/my-page/EditProfilePage.tsx
  src/types/auth.d.ts
Labels: feat

#113 fix: 프로필 수정시 현재 유저 정보 보여주기
  src/pages/my-page/EditProfilePage.tsx
Labels: fix

#108 Feat: 매칭 대기화면 전환 및 채팅방 참가 로직 추가
  src/assets/icon/matching-loading/circleIcon.svg
  src/assets/icon/matching-loading/taxiSideIcon.svg
  src/components/chat/bottomMenu/index.tsx
  src/components/notification/FriendRequestNotification.tsx
  src/components/notification/MatchingNotification.tsx
  src/components/notification/index.tsx
  src/components/toast/index.tsx
  src/hooks/queries/useInfiniteScroll.ts
  src/index.css
  src/pages/matching/index.tsx
  src/pages/mathcing/index.tsx
  src/store/useSSEStore.ts
  src/types/manual.d.ts
  src/types/match.d.ts
Labels: feat

#116 Feat: 오류 error 페이지 구현
  src/assets/icon/errorIcon.svg
  src/components/error/index.tsx
  src/pages/chat/index.tsx
Labels: feat, design

#117 Fix: 프로필 수정 로직 변경
  src/components/commons/Input.tsx
  src/components/modal/AccountNumberModal.tsx
  src/components/my-page/MyProfileHeader.tsx
  src/hooks/useChangeButtonData.tsx
  src/libs/apis/getAccountNumber.api.ts
  src/libs/schemas/auth.ts
  src/pages/my-page/EditProfilePage.tsx
  src/pages/my-page/index.tsx
  src/types/auth.d.ts
Labels: feat

#119 feat: 회원 탈퇴하기 api 연결
  src/hooks/useWithdraw.ts
  src/libs/apis/withdrawUser.api.ts
Labels: feat

#120 Feat: 자잘한 변경 사항 수정 (1)
  index.html
  src/assets/icon/chattingRoomIcon.svg
  src/components/chat/bottomMenu/index.tsx
  src/components/commons/Button.tsx
  src/components/home/FriendList/BlackListPage.tsx
  src/components/home/FriendList/FriendInfoItem.tsx
  src/components/home/FriendList/FriendListPage.tsx
  src/components/home/FriendList/index.tsx
  src/components/home/Navbar.tsx
  src/components/home/autoMatching/index.tsx
  src/components/home/autoMatching/inviteMembers/index.tsx
  src/components/home/chatLink/index.tsx
  src/components/home/manualMatching/MatchingPage.tsx
  src/components/home/manualMatching/MyMatchingPage.tsx
  src/components/home/manualMatching/matchingInfoItem/index.tsx
  src/components/modal/AgreementModal.tsx
  src/components/modal/FriendDeleteOrBlack.tsx
  src/components/notification/FriendRequestNotification.tsx
  src/components/notification/index.tsx
  src/components/sign/AuthCodeVerification.tsx
  src/components/sign/EmailVerification.tsx
  src/components/sign/userInfoVerification/index.tsx
  src/constants/errorMessage.constant.ts
  src/constants/index.ts
  src/hooks/mutations/useAcceptFriend.ts
  src/hooks/mutations/useDeleteBlackList.ts
  src/hooks/mutations/useDeleteNotification.ts
  src/hooks/mutations/useFriendReply.ts
  src/hooks/mutations/useFriendToBlack.ts
  src/hooks/mutations/useInviteReply.ts
  src/hooks/queries/useBlackList.ts
  src/libs/apis/addBlackList.api.ts
  src/libs/apis/blackList/addToBlackList.api.ts
  src/libs/apis/blackList/deleteToBlackList.api.ts
  src/libs/apis/blackList/getToBlackList.api.ts
  src/libs/apis/deleteBlackList.api.ts
  src/libs/apis/friends/getFriends.api.ts
  src/libs/apis/friends/replyFriendRequest.api.ts
  src/libs/apis/getBlackList.api.ts
  src/libs/apis/manual/replyManualMatchingInvite.api.ts
  src/libs/schemas/match.ts
  src/pages/friend-request/index.tsx
  src/pages/home/index.tsx
  src/pages/manual-register/index.tsx
  src/pages/matching/index.tsx
  src/store/useChattingRoomId.ts
  src/types/friend.d.ts
  src/types/match.d.ts
  src/types/notification.d.ts
Labels: feat

#123 Fix: 매칭 취소 api 수정
  index.html
  src/components/chat/bottomMenu/index.tsx
  src/components/commons/BackButton.tsx
  src/libs/apis/getCloseMatching.api.ts
  src/libs/apis/getExitChatRoom.ts
  src/pages/chat/index.tsx
Labels: fix

#126 Feat: 자잘한 변경사항 수정 (2)
  src/App.tsx
  src/components/chat/bottomMenu/index.tsx
  src/components/home/FriendList/FriendListPage.tsx
  src/components/home/autoMatching/RouteSetting.tsx
  src/components/home/autoMatching/index.tsx
  src/components/home/autoMatching/inviteMembers/index.tsx
  src/components/home/autoMatching/selectTags/index.tsx
  src/components/home/manualMatching/matchingInfoItem/index.tsx
  src/components/manual-register/AddContent.tsx
  src/libs/apis/clients.ts
  src/libs/apis/deleteBlackList.api.ts
  src/libs/schemas/match.ts
  src/pages/manual-register/index.tsx
  src/pages/matching/index.tsx
  src/types/match.d.ts
Labels: feat

#128 Fix: 변경사항 수정
  src/components/chat/bottomMenu/index.tsx
  src/pages/chat/index.tsx
Labels: fix

#133 Feat: 시연 때 발생한 오류 및 에러 페이지 적용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icon/xIcon.svg
  src/components/error/ReactErrorBoundary.tsx
  src/components/error/index.tsx
  src/components/home/FriendList/BlackInfoItem.tsx
  src/components/home/autoMatching/index.tsx
  src/components/home/manualMatching/matchingInfoItem/Tags.tsx
  src/components/home/manualMatching/matchingInfoItem/index.tsx
  src/components/loading/InviteMembersLoading.tsx
  src/components/modal/index.tsx
  src/pages/manual-register/index.tsx
  src/types/blackList.d.ts
Labels: feat, fix
